# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  frontend build:
    runs-on: ubuntu-latest

    stategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      working-directory: ./services/frontend
      run: npm i
    - name: Run build
      run: npm run build --if-present
  tsLint:
    runs-on: ubuntu-latest

    stategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      working-directory: ./services/frontend
      run: cp . .
      run: npm i
    - name: Run build
      run: npm run tslint

